# Form implementation generated from reading ui file 'interviews.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 590)
        Form.setMinimumSize(QtCore.QSize(750, 590))
        Form.setMaximumSize(QtCore.QSize(750, 590))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 171))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pictures/interviews_menu.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(210, 12, 261, 101))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pictures/wehere_logo.ico"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(470, 40, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.label_3.setObjectName("label_3")
        self.pushButton_inter_exit = QtWidgets.QPushButton(parent=Form)
        self.pushButton_inter_exit.setGeometry(QtCore.QRect(20, 530, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButton_inter_exit.setFont(font)
        self.pushButton_inter_exit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButton_inter_exit.setObjectName("pushButton_inter_exit")
        self.pushButton_inter_preferences = QtWidgets.QPushButton(parent=Form)
        self.pushButton_inter_preferences.setGeometry(QtCore.QRect(20, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButton_inter_preferences.setFont(font)
        self.pushButton_inter_preferences.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButton_inter_preferences.setObjectName("pushButton_inter_preferences")
        self.pushButton_inter_sub_projects = QtWidgets.QPushButton(parent=Form)
        self.pushButton_inter_sub_projects.setGeometry(QtCore.QRect(20, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButton_inter_sub_projects.setFont(font)
        self.pushButton_inter_sub_projects.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButton_inter_sub_projects.setObjectName("pushButton_inter_sub_projects")
        self.lineEdit_inter_username = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_inter_username.setEnabled(True)
        self.lineEdit_inter_username.setGeometry(QtCore.QRect(20, 200, 171, 31))
        self.lineEdit_inter_username.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEdit_inter_username.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgb(36, 36, 36);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_inter_username.setText("")
        self.lineEdit_inter_username.setObjectName("lineEdit_inter_username")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(210, 200, 511, 361))
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.pushButton_inter_search = QtWidgets.QPushButton(parent=Form)
        self.pushButton_inter_search.setGeometry(QtCore.QRect(20, 250, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButton_inter_search.setFont(font)
        self.pushButton_inter_search.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButton_inter_search.setObjectName("pushButton_inter_search")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(420, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.label_4.setObjectName("label_4")
        self.pushButton_inter_pro_arrivals = QtWidgets.QPushButton(parent=Form)
        self.pushButton_inter_pro_arrivals.setGeometry(QtCore.QRect(20, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButton_inter_pro_arrivals.setFont(font)
        self.pushButton_inter_pro_arrivals.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButton_inter_pro_arrivals.setObjectName("pushButton_inter_pro_arrivals")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "INTERVIEWS"))
        self.label_3.setText(_translate("Form", "INTERVIEWS "))
        self.pushButton_inter_exit.setText(_translate("Form", "Exit"))
        self.pushButton_inter_preferences.setText(_translate("Form", "Preferences"))
        self.pushButton_inter_sub_projects.setText(_translate("Form", "Submitted Projects"))
        self.lineEdit_inter_username.setPlaceholderText(_translate("Form", "      Name or Surname"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name Surname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Project \n"
"Submission Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Project \n"
"Arrival Date"))
        self.pushButton_inter_search.setText(_translate("Form", "Search"))
        self.label_4.setText(_translate("Form", "MENU"))
        self.pushButton_inter_pro_arrivals.setText(_translate("Form", "Project Arrivals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
