# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        MainWindow.setWindowTitle("LOGIN")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/wehere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"One value - border-radius: 100px;")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(86, 200, 91, 31))
        self.pushButton_login.setMouseTracking(True)
        self.pushButton_login.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}\n"
"")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(186, 200, 91, 31))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}\n"
"")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setEnabled(True)
        self.lineEdit_username.setGeometry(QtCore.QRect(80, 100, 191, 31))
        self.lineEdit_username.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgb(36, 36, 36);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(80, 140, 191, 31))
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgb(36, 36, 36);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(40, 20, 251, 71))
        self.label_logo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("pictures/wehere_logo.ico"))
        self.label_logo.setObjectName("label_logo")
        self.pushButton_forgot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_forgot.setGeometry(QtCore.QRect(90, 250, 181, 31))
        self.pushButton_forgot.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(107, 107, 107);\n"
"}")
        self.pushButton_forgot.setObjectName("pushButton_forgot")
        self.label_fail = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_fail.setGeometry(QtCore.QRect(40, 175, 261, 21))
        self.label_fail.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"color: rgba(255, 0, 0, 0.5);\n"
"border-radius : 15px;")
        self.label_fail.setScaledContents(False)
        self.label_fail.setObjectName("label_fail")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.pushButton_forgot.setText(_translate("MainWindow", "Forgot password.?"))
        self.label_fail.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
