# Form implementation generated from reading ui file 'user_preference.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/wehere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(120, 20, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pictures/wehere_logo.ico"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 341, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pictures/user_loop.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_user_pre_applications = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user_pre_applications.setGeometry(QtCore.QRect(213, 155, 75, 75))
        self.pushButton_user_pre_applications.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_user_pre_applications.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_user_pre_applications.setFont(font)
        self.pushButton_user_pre_applications.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    \n"
"    background-color: rgb(0, 204, 209);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 251, 255);\n"
"}\n"
"")
        self.pushButton_user_pre_applications.setObjectName("pushButton_user_pre_applications")
        self.pushButton_user_pre_interviews = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user_pre_interviews.setGeometry(QtCore.QRect(318, 223, 75, 75))
        self.pushButton_user_pre_interviews.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_user_pre_interviews.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_user_pre_interviews.setFont(font)
        self.pushButton_user_pre_interviews.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(0, 108, 143);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 196, 255);\n"
"}\n"
"")
        self.pushButton_user_pre_interviews.setObjectName("pushButton_user_pre_interviews")
        self.pushButton_user_pre_exit = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user_pre_exit.setGeometry(QtCore.QRect(278, 341, 75, 75))
        self.pushButton_user_pre_exit.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_user_pre_exit.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_user_pre_exit.setFont(font)
        self.pushButton_user_pre_exit.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(243, 199, 65);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(162, 132, 43);\n"
"}\n"
"")
        self.pushButton_user_pre_exit.setObjectName("pushButton_user_pre_exit")
        self.pushButton_user_pre_main_menu = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user_pre_main_menu.setGeometry(QtCore.QRect(149, 341, 75, 75))
        self.pushButton_user_pre_main_menu.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_user_pre_main_menu.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_user_pre_main_menu.setFont(font)
        self.pushButton_user_pre_main_menu.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 140, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(170, 92, 41);\n"
"}\n"
"")
        self.pushButton_user_pre_main_menu.setObjectName("pushButton_user_pre_main_menu")
        self.pushButton_user_pre_mentor_meeting = QtWidgets.QPushButton(parent=Form)
        self.pushButton_user_pre_mentor_meeting.setGeometry(QtCore.QRect(107, 224, 75, 75))
        self.pushButton_user_pre_mentor_meeting.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButton_user_pre_mentor_meeting.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_user_pre_mentor_meeting.setFont(font)
        self.pushButton_user_pre_mentor_meeting.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 109, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(173, 73, 69);\n"
"}\n"
"")
        self.pushButton_user_pre_mentor_meeting.setObjectName("pushButton_user_pre_mentor_meeting")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(200, 245, 100, 100))
        self.label_3.setMinimumSize(QtCore.QSize(100, 100))
        self.label_3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("pictures/user_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "USER PREFENCE"))
        self.pushButton_user_pre_applications.setText(_translate("Form", "Applications"))
        self.pushButton_user_pre_interviews.setText(_translate("Form", "Interviews"))
        self.pushButton_user_pre_exit.setText(_translate("Form", "Exit"))
        self.pushButton_user_pre_main_menu.setText(_translate("Form", "Main Menu"))
        self.pushButton_user_pre_mentor_meeting.setText(_translate("Form", "Mentor\n"
"Meeting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
